-- Auto-generated fact table definitions for 10km grid
-- Generated by scripts/generate_schema.py
-- Data types determined by inspecting actual data values (decimal comma detection)


-- Alter_INFR fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_alter_infr (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung NUMERIC,
    unter3 NUMERIC,
    a3bis5 NUMERIC,
    a6bis9 NUMERIC,
    a10bis15 NUMERIC,
    a16bis18 NUMERIC,
    a19bis24 NUMERIC,
    a25bis39 NUMERIC,
    a40bis59 NUMERIC,
    a60bis66 NUMERIC,
    a67bis74 NUMERIC,
    a75undaelter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Alter_in_10er-Jahresgruppen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_alter_in_10er_jahresgruppen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung NUMERIC,
    unter10 NUMERIC,
    a10bis19 NUMERIC,
    a20bis29 NUMERIC,
    a30bis39 NUMERIC,
    a40bis49 NUMERIC,
    a50bis59 NUMERIC,
    a60bis69 NUMERIC,
    a70bis79 NUMERIC,
    a80undaelter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Alter_in_5_Altersklassen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_alter_in_5_altersklassen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung NUMERIC,
    unter18 NUMERIC,
    a18bis29 NUMERIC,
    a30bis49 NUMERIC,
    a50bis64 NUMERIC,
    a65undaelter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Anteil_Auslaender fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_anteil_auslaender (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilauslaender NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Anteil_ueber_65 fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_anteil_ueber_65 (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilueber65 NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Anteil_unter_18 fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_anteil_unter_18 (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilunter18 NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Auslaenderanteil_ab18 fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_auslaenderanteil_ab18 (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilauslaenderab18 NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Baujahr_JZ fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_baujahr_jz (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude NUMERIC,
    vor1919 NUMERIC,
    a1919bis1949 NUMERIC,
    a1950bis1959 NUMERIC,
    a1960bis1969 NUMERIC,
    a1970bis1979 NUMERIC,
    a1980bis1989 NUMERIC,
    a1990bis1999 NUMERIC,
    a2000bis2009 NUMERIC,
    a2010bis2015 NUMERIC,
    a2016undspaeter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Bevoelkerungszahl fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_bevoelkerungszahl (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    einwohner INTEGER,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Deutsche_Staatsangehoerige_ab18 fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_deutsche_staatsangehoerige_ab18 (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    deutsche_ab18 INTEGER,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschn_Flaeche_je_Bewohner fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschn_flaeche_je_bewohner (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnflaechejebew NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschn_Flaeche_je_Wohnung fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschn_flaeche_je_wohnung (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnflaechejewohn NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschn_Haushaltsgroesse fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschn_haushaltsgroesse (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnhhgroesse NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschn_Nettokaltmiete fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschn_nettokaltmiete (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnmieteqm NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschnittliche_Nettokaltmiete_und_Anzahl_der_Wohnungen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschnittliche_nettokaltmiete_und_anzahl_der_wohnungen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnmieteqm NUMERIC,
    anzahlwohnungen NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschnittsalter fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschnittsalter (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnittsalter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Eigentuemerquote fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_eigentuemerquote (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    eigentuemerquote NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Energietraeger fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_energietraeger (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_energietraeger NUMERIC,
    gas NUMERIC,
    heizoel NUMERIC,
    holz_holzpellets NUMERIC,
    biomasse_biogas NUMERIC,
    solar_geothermie_waermepumpen NUMERIC,
    strom NUMERIC,
    kohle NUMERIC,
    fernwaerme NUMERIC,
    kein_energietraeger NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Familienstand fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_familienstand (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung NUMERIC,
    ledig NUMERIC,
    verheiratet NUMERIC,
    verwitwet NUMERIC,
    geschieden NUMERIC,
    eingetrlebenspartnerschaft NUMERIC,
    eingetrlebenspartverstorben NUMERIC,
    eingetrlebenspartaufgehoben NUMERIC,
    ohneangabe NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Flaeche_der_Wohnung_10m2_Intervalle fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_flaeche_der_wohnung_10m2_intervalle (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_wohnungen NUMERIC,
    unter30 NUMERIC,
    col_30bis39 NUMERIC,
    col_40bis49 NUMERIC,
    col_50bis59 NUMERIC,
    col_60bis69 NUMERIC,
    col_70bis79 NUMERIC,
    col_80bis89 NUMERIC,
    col_90bis99 NUMERIC,
    col_100bis109 NUMERIC,
    col_110bis119 NUMERIC,
    col_120bis129 NUMERIC,
    col_130bis139 NUMERIC,
    col_140bis149 NUMERIC,
    col_150bis159 NUMERIC,
    col_160bis169 NUMERIC,
    col_170bis179 NUMERIC,
    col_180undmehr NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Geb_Gebaeudetyp_Groesse fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_geb_gebaeudetyp_groesse (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude NUMERIC,
    freiefh NUMERIC,
    efh_dhh NUMERIC,
    efh_reihenhaus NUMERIC,
    freist_zfh NUMERIC,
    zfh_dhh NUMERIC,
    zfh_reihenhaus NUMERIC,
    mfh_3bis6wohnungen NUMERIC,
    mfh_7bis12wohnungen NUMERIC,
    mfh_13undmehrwohnungen NUMERIC,
    anderergebaeudetyp NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_Anzahl_der_Wohnungen_im_Gebaeude fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_gebaeude_mit_wohnraum_nach_anzahl_der_wohnungen_im_gebaeude (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude NUMERIC,
    col_1_wohnung NUMERIC,
    col_2_wohnungen NUMERIC,
    col_3bis6_wohnungen NUMERIC,
    col_7bis12_wohnungen NUMERIC,
    col_13undmehr_wohnungen NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_Energietraeger_der_Heizung fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_gebaeude_mit_wohnraum_nach_energietraeger_der_heizung (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_energietraeger NUMERIC,
    gas NUMERIC,
    heizoel NUMERIC,
    holz_holzpellets NUMERIC,
    biomasse_biogas NUMERIC,
    solar_geothermie_waermepumpen NUMERIC,
    strom NUMERIC,
    kohle NUMERIC,
    fernwaerme NUMERIC,
    kein_energietraeger NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_ueberwiegender_Heizungsart fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_gebaeude_mit_wohnraum_nach_ueberwiegender_heizungsart (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_heizungsart NUMERIC,
    fernheizung NUMERIC,
    etagenheizung NUMERIC,
    blockheizung NUMERIC,
    zentralheizung NUMERIC,
    einzel_mehrraumoefen NUMERIC,
    keine_heizung NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Gebaeude_nach_Baujahr_in_Mikrozensus_Klassen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_gebaeude_nach_baujahr_in_mikrozensus_klassen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude NUMERIC,
    vor1919 NUMERIC,
    a1919bis1948 NUMERIC,
    a1949bis1978 NUMERIC,
    a1979bis1990 NUMERIC,
    a1991bis2000 NUMERIC,
    a2001bis2010 NUMERIC,
    a2011bis2019 NUMERIC,
    a2020undspaeter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Geburtsland_Gruppen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_geburtsland_gruppen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung NUMERIC,
    deutschland NUMERIC,
    ausland_sonstige NUMERIC,
    eu27_land NUMERIC,
    sonstiges_europa NUMERIC,
    sonstige_welt NUMERIC,
    sonstige NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Groesse_des_privaten_Haushalts fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_groesse_des_privaten_haushalts (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung NUMERIC,
    col_1_person NUMERIC,
    col_2_personen NUMERIC,
    col_3_personen NUMERIC,
    col_4_personen NUMERIC,
    col_5_personen NUMERIC,
    col_6_personen_und_mehr NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Grosse_Kernfamilie_bis6undmehrPers fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_grosse_kernfamilie_bis6undmehrpers (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_familien NUMERIC,
    a2personen NUMERIC,
    a3personen NUMERIC,
    a4personen NUMERIC,
    a5personen NUMERIC,
    a6pers_und_mehr NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Heizungsart fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_heizungsart (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_heizungsart NUMERIC,
    fernheizung NUMERIC,
    etagenheizung NUMERIC,
    blockheizung NUMERIC,
    zentralheizung NUMERIC,
    einzel_mehrraumoefen NUMERIC,
    keine_heizung NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Leerstandsquote fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_leerstandsquote (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    leerstandsquote NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Marktaktive_Leerstandsquote fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_marktaktive_leerstandsquote (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    marktaktive_leerstandsquote NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Religion fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_religion (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung NUMERIC,
    roemisch_katholisch NUMERIC,
    evangelisch NUMERIC,
    sonstige_keine_ohneangabe NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Seniorenstatus_eines_privaten_Haushalts fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_seniorenstatus_eines_privaten_haushalts (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_haushalte NUMERIC,
    hh_nursenioren NUMERIC,
    hh_mitsenioren NUMERIC,
    hh_ohnesenioren NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Staatsangehoerigkeit fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_staatsangehoerigkeit (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung NUMERIC,
    deutschland NUMERIC,
    ausland_sonstige NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Staatsangehoerigkeit_Gruppen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_staatsangehoerigkeit_gruppen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung NUMERIC,
    deutschland NUMERIC,
    ausland_sonstige NUMERIC,
    eu27_land NUMERIC,
    sonstiges_europa NUMERIC,
    sonstige_welt NUMERIC,
    sonstige NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Typ_der_Kernfamilie_nach_Kindern fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_typ_der_kernfamilie_nach_kindern (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_familie NUMERIC,
    ehep_ohnekind NUMERIC,
    ehep_mind_1kind_unter18 NUMERIC,
    ehep_kinder_ab18 NUMERIC,
    eingetrlp_ohnekind NUMERIC,
    eingetrlp_mind_1kind_unter18 NUMERIC,
    eingetrlp_kinder_ab18 NUMERIC,
    nichtehellg_ohnekind NUMERIC,
    nichtehellg_mind_1kind_unter18 NUMERIC,
    nichtehellg_kinder_ab18 NUMERIC,
    vater_mind_1kind_unter18 NUMERIC,
    vater_kinder_ab18 NUMERIC,
    mutter_mind_1kind_unter18 NUMERIC,
    mutter_kinder_ab18 NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Typ_priv_HH_Familie fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_typ_priv_hh_familie (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_haushalte NUMERIC,
    einpershh_singlehh NUMERIC,
    paare_ohnekind NUMERIC,
    paare_mitkind NUMERIC,
    alleinerziehende NUMERIC,
    mehrpershhohnekernfam NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Typ_priv_HH_Lebensform fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_typ_priv_hh_lebensform (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_haushalte NUMERIC,
    einpershh_singlehh NUMERIC,
    ehepaare NUMERIC,
    eingetrlebensp NUMERIC,
    nichtehellebensg NUMERIC,
    alleinerzmuetter NUMERIC,
    alleinerzvaeter NUMERIC,
    mehrpershhohnekernfam NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Wohnung_Gebaeudetyp_Groesse fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_wohnung_gebaeudetyp_groesse (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_wohnungen NUMERIC,
    freiefh NUMERIC,
    efh_dhh NUMERIC,
    efh_reihenhaus NUMERIC,
    freist_zfh NUMERIC,
    zfh_dhh NUMERIC,
    zfh_reihenhaus NUMERIC,
    mfh_3bis6wohnungen NUMERIC,
    mfh_7bis12wohnungen NUMERIC,
    mfh_13undmehrwohnungen NUMERIC,
    anderergebaeudetyp NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Wohnungen_nach_Zahl_der_Raeume fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_wohnungen_nach_zahl_der_raeume (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_wohnungen NUMERIC,
    col_1raum NUMERIC,
    col_2raeume NUMERIC,
    col_3raeume NUMERIC,
    col_4raeume NUMERIC,
    col_5raeume NUMERIC,
    col_6raeume NUMERIC,
    col_7undmehrraeume NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Zahl_der_Staatsangehoerigkeiten fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_zahl_der_staatsangehoerigkeiten (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung NUMERIC,
    einestaatsang NUMERIC,
    mehrere_deutsch_und_auslaendisch NUMERIC,
    mehrere_nur_auslaendisch NUMERIC,
    nicht_bekannt NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);

