-- Create schema for Zensus data
CREATE SCHEMA IF NOT EXISTS zensus;

-- Reference Tables (with geometry, SRID 3035)
-- These tables store the authoritative polygon geometries from GeoGitter INSPIRE

-- 1km grid reference table
CREATE TABLE IF NOT EXISTS zensus.ref_grid_1km (
    grid_id TEXT PRIMARY KEY,
    geom GEOMETRY(POLYGON, 3035) NOT NULL,
    CONSTRAINT chk_grid_1km_valid CHECK (ST_IsValid(geom)),
    CONSTRAINT chk_grid_1km_srid CHECK (ST_SRID(geom) = 3035)
);

-- 10km grid reference table
CREATE TABLE IF NOT EXISTS zensus.ref_grid_10km (
    grid_id TEXT PRIMARY KEY,
    geom GEOMETRY(POLYGON, 3035) NOT NULL,
    CONSTRAINT chk_grid_10km_valid CHECK (ST_IsValid(geom)),
    CONSTRAINT chk_grid_10km_srid CHECK (ST_SRID(geom) = 3035)
);

-- 100m grid reference table
CREATE TABLE IF NOT EXISTS zensus.ref_grid_100m (
    grid_id TEXT PRIMARY KEY,
    geom GEOMETRY(POLYGON, 3035) NOT NULL,
    CONSTRAINT chk_grid_100m_valid CHECK (ST_IsValid(geom)),
    CONSTRAINT chk_grid_100m_srid CHECK (ST_SRID(geom) = 3035)
);

-- Fact Tables (no geometry, joined via grid_id)
-- These tables store Zensus statistical data
-- Auto-generated from all CSV files in data/zensus_data/

-- Note: All fact tables follow the pattern: fact_zensus_{grid_size}_{sanitized_folder_name}
-- Run scripts/generate_schema.py to regenerate these definitions if CSV structure changes

-- Future: Election data tables (placeholder)
-- CREATE TABLE IF NOT EXISTS zensus.ref_wahlkreis (
--     wahlkreis_id SERIAL PRIMARY KEY,
--     election_year INTEGER NOT NULL,
--     wahlkreis_nr INTEGER NOT NULL,
--     name TEXT,
--     geom GEOMETRY(MULTIPOLYGON, 3035) NOT NULL,
--     CONSTRAINT chk_wahlkreis_valid CHECK (ST_IsValid(geom)),
--     CONSTRAINT chk_wahlkreis_srid CHECK (ST_SRID(geom) = 3035),
--     CONSTRAINT chk_wahlkreis_nr CHECK (wahlkreis_nr BETWEEN 1 AND 299),
--     CONSTRAINT uq_wahlkreis_year_nr UNIQUE (election_year, wahlkreis_nr)
-- );

-- CREATE TABLE IF NOT EXISTS zensus.ref_wahlbezirk (
--     wahlbezirk_id SERIAL PRIMARY KEY,
--     election_year INTEGER NOT NULL,
--     ags TEXT NOT NULL,
--     wahlbez_nr INTEGER NOT NULL,
--     wahlkreis_id INTEGER,
--     geom GEOMETRY(POLYGON, 3035) NOT NULL,
--     CONSTRAINT chk_wahlbezirk_valid CHECK (ST_IsValid(geom)),
--     CONSTRAINT chk_wahlbezirk_srid CHECK (ST_SRID(geom) = 3035),
--     CONSTRAINT fk_wahlkreis FOREIGN KEY (wahlkreis_id) REFERENCES zensus.ref_wahlkreis(wahlkreis_id),
--     CONSTRAINT uq_wahlbezirk_year_ags_nr UNIQUE (election_year, ags, wahlbez_nr)
-- );

-- Future: Bridge tables for spatial intersections (placeholder)
-- CREATE TABLE IF NOT EXISTS zensus.bridge_grid100_wahlkreis (
--     grid_id TEXT NOT NULL,
--     wahlkreis_id INTEGER NOT NULL,
--     area_share NUMERIC NOT NULL,
--     CONSTRAINT chk_area_share CHECK (area_share BETWEEN 0 AND 1),
--     CONSTRAINT fk_grid_100m FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_100m(grid_id),
--     CONSTRAINT fk_wahlkreis FOREIGN KEY (wahlkreis_id) REFERENCES zensus.ref_wahlkreis(wahlkreis_id),
--     PRIMARY KEY (grid_id, wahlkreis_id)
-- );

-- Auto-generated fact table definitions for all Zensus datasets
-- Generated by scripts/generate_schema.py


-- Alter_in_10er-Jahresgruppen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_alter_in_10er_jahresgruppen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    unter10 NUMERIC,
    a10bis19 NUMERIC,
    a20bis29 NUMERIC,
    a30bis39 NUMERIC,
    a40bis49 NUMERIC,
    a50bis59 NUMERIC,
    a60bis69 NUMERIC,
    a70bis79 NUMERIC,
    a80undaelter NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Alter_in_10er-Jahresgruppen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_alter_in_10er_jahresgruppen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    unter10 NUMERIC,
    a10bis19 NUMERIC,
    a20bis29 NUMERIC,
    a30bis39 NUMERIC,
    a40bis49 NUMERIC,
    a50bis59 NUMERIC,
    a60bis69 NUMERIC,
    a70bis79 NUMERIC,
    a80undaelter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Alter_in_5_Altersklassen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_alter_in_5_altersklassen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    unter18 NUMERIC,
    a18bis29 NUMERIC,
    a30bis49 NUMERIC,
    a50bis64 NUMERIC,
    a65undaelter NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Alter_in_5_Altersklassen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_alter_in_5_altersklassen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    unter18 NUMERIC,
    a18bis29 NUMERIC,
    a30bis49 NUMERIC,
    a50bis64 NUMERIC,
    a65undaelter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Alter_in_infrastrukturellen_Altersgruppen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_alter_in_infrastrukturellen_altersgruppen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    unter3 NUMERIC,
    a3bis5 NUMERIC,
    a6bis9 NUMERIC,
    a10bis15 NUMERIC,
    a16bis18 NUMERIC,
    a19bis24 NUMERIC,
    a25bis39 NUMERIC,
    a40bis59 NUMERIC,
    a60bis66 NUMERIC,
    a67bis74 NUMERIC,
    a75undaelter NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Alter_in_infrastrukturellen_Altersgruppen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_alter_in_infrastrukturellen_altersgruppen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    unter3 NUMERIC,
    a3bis5 NUMERIC,
    a6bis9 NUMERIC,
    a10bis15 NUMERIC,
    a16bis18 NUMERIC,
    a19bis24 NUMERIC,
    a25bis39 NUMERIC,
    a40bis59 NUMERIC,
    a60bis66 NUMERIC,
    a67bis74 NUMERIC,
    a75undaelter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Anteil_ab_65-jaehrige_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_anteil_ab_65_jaehrige_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilueber65 NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Anteil_ab_65-jaehrige_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_anteil_ab_65_jaehrige_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilueber65 NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Anteil_unter_18-jaehrige_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_anteil_unter_18_jaehrige_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilunter18 NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Anteil_unter_18-jaehrige_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_anteil_unter_18_jaehrige_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilunter18 NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Auslaenderanteil_ab_18_Jahren fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_auslaenderanteil_ab_18_jahren (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilauslaenderab18 NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Auslaenderanteil_ab_18_Jahren fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_auslaenderanteil_ab_18_jahren (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilauslaenderab18 NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Auslaenderanteil_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_auslaenderanteil_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilauslaender NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Auslaenderanteil_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_auslaenderanteil_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    anteilauslaender NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Deutsche_Staatsangehoerige_ab_18_Jahren fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_deutsche_staatsangehoerige_ab_18_jahren (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    deutsche_ab18 NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Deutsche_Staatsangehoerige_ab_18_Jahren fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_deutsche_staatsangehoerige_ab_18_jahren (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    deutsche_ab18 NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschnittliche_Flaeche_je_Wohnung_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_durchschnittliche_flaeche_je_wohnung_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnflaechejewohn NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Durchschnittliche_Flaeche_je_Wohnung_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschnittliche_flaeche_je_wohnung_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnflaechejewohn NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschnittliche_Haushaltsgroesse_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_durchschnittliche_haushaltsgroesse_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnhhgroesse NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Durchschnittliche_Haushaltsgroesse_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschnittliche_haushaltsgroesse_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnhhgroesse NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschnittliche_Nettokaltmiete_und_Anzahl_der_Wohnungen_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_durchschnittliche_nettokaltmiete_und_anzahl_der_wohnungen_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnmieteqm NUMERIC,
    anzahlwohnungen INTEGER,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Durchschnittliche_Nettokaltmiete_und_Anzahl_der_Wohnungen_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschnittliche_nettokaltmiete_und_anzahl_der_wohnungen_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnmieteqm NUMERIC,
    anzahlwohnungen INTEGER,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschnittliche_Wohnflaeche_je_Bewohner_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_durchschnittliche_wohnflaeche_je_bewohner_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnflaechejebew NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Durchschnittliche_Wohnflaeche_je_Bewohner_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschnittliche_wohnflaeche_je_bewohner_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnflaechejebew NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Durchschnittsalter_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_durchschnittsalter_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnittsalter NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Durchschnittsalter_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_durchschnittsalter_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnittsalter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Eigentuemerquote_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_eigentuemerquote_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    eigentuemerquote NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Eigentuemerquote_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_eigentuemerquote_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    eigentuemerquote NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Familienstand_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_familienstand_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    ledig NUMERIC,
    verheiratet NUMERIC,
    verwitwet NUMERIC,
    geschieden NUMERIC,
    eingetrlebenspartnerschaft NUMERIC,
    eingetrlebenspartverstorben NUMERIC,
    eingetrlebenspartaufgehoben NUMERIC,
    ohneangabe NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Familienstand_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_familienstand_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    ledig NUMERIC,
    verheiratet NUMERIC,
    verwitwet NUMERIC,
    geschieden NUMERIC,
    eingetrlebenspartnerschaft NUMERIC,
    eingetrlebenspartverstorben NUMERIC,
    eingetrlebenspartaufgehoben NUMERIC,
    ohneangabe NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Flaeche_der_Wohnung_10m2_Intervalle fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_flaeche_der_wohnung_10m2_intervalle (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_wohnungen INTEGER,
    unter30 NUMERIC,
    30bis39 NUMERIC,
    40bis49 NUMERIC,
    50bis59 NUMERIC,
    60bis69 NUMERIC,
    70bis79 NUMERIC,
    80bis89 NUMERIC,
    90bis99 NUMERIC,
    100bis109 NUMERIC,
    110bis119 NUMERIC,
    120bis129 NUMERIC,
    130bis139 NUMERIC,
    140bis149 NUMERIC,
    150bis159 NUMERIC,
    160bis169 NUMERIC,
    170bis179 NUMERIC,
    180undmehr NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Flaeche_der_Wohnung_10m2_Intervalle fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_flaeche_der_wohnung_10m2_intervalle (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_wohnungen INTEGER,
    unter30 NUMERIC,
    30bis39 NUMERIC,
    40bis49 NUMERIC,
    50bis59 NUMERIC,
    60bis69 NUMERIC,
    70bis79 NUMERIC,
    80bis89 NUMERIC,
    90bis99 NUMERIC,
    100bis109 NUMERIC,
    110bis119 NUMERIC,
    120bis129 NUMERIC,
    130bis139 NUMERIC,
    140bis149 NUMERIC,
    150bis159 NUMERIC,
    160bis169 NUMERIC,
    170bis179 NUMERIC,
    180undmehr NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_Anzahl_der_Wohnungen_im_Gebaeude fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_gebaeude_mit_wohnraum_nach_anzahl_der_wohnungen_im_gebaeude (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude INTEGER,
    1_wohnung NUMERIC,
    2_wohnungen INTEGER,
    3bis6_wohnungen INTEGER,
    7bis12_wohnungen INTEGER,
    13undmehr_wohnungen INTEGER,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_Anzahl_der_Wohnungen_im_Gebaeude fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_gebaeude_mit_wohnraum_nach_anzahl_der_wohnungen_im_gebaeude (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude INTEGER,
    1_wohnung NUMERIC,
    2_wohnungen INTEGER,
    3bis6_wohnungen INTEGER,
    7bis12_wohnungen INTEGER,
    13undmehr_wohnungen INTEGER,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_Energietraeger_der_Heizung fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_gebaeude_mit_wohnraum_nach_energietraeger_der_heizung (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_energietraeger NUMERIC,
    gas NUMERIC,
    heizoel NUMERIC,
    holz_holzpellets NUMERIC,
    biomasse_biogas NUMERIC,
    solar_geothermie_waermepumpen NUMERIC,
    strom NUMERIC,
    kohle NUMERIC,
    fernwaerme NUMERIC,
    kein_energietraeger NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_Energietraeger_der_Heizung fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_gebaeude_mit_wohnraum_nach_energietraeger_der_heizung (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_energietraeger NUMERIC,
    gas NUMERIC,
    heizoel NUMERIC,
    holz_holzpellets NUMERIC,
    biomasse_biogas NUMERIC,
    solar_geothermie_waermepumpen NUMERIC,
    strom NUMERIC,
    kohle NUMERIC,
    fernwaerme NUMERIC,
    kein_energietraeger NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_Gebaeudetyp_Groesse fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_gebaeude_mit_wohnraum_nach_gebaeudetyp_groesse (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude INTEGER,
    freiefh NUMERIC,
    efh_dhh NUMERIC,
    efh_reihenhaus NUMERIC,
    freist_zfh NUMERIC,
    zfh_dhh NUMERIC,
    zfh_reihenhaus NUMERIC,
    mfh_3bis6wohnungen INTEGER,
    mfh_7bis12wohnungen INTEGER,
    mfh_13undmehrwohnungen INTEGER,
    anderergebaeudetyp INTEGER,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_Gebaeudetyp_Groesse fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_gebaeude_mit_wohnraum_nach_gebaeudetyp_groesse (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude INTEGER,
    freiefh NUMERIC,
    efh_dhh NUMERIC,
    efh_reihenhaus NUMERIC,
    freist_zfh NUMERIC,
    zfh_dhh NUMERIC,
    zfh_reihenhaus NUMERIC,
    mfh_3bis6wohnungen INTEGER,
    mfh_7bis12wohnungen INTEGER,
    mfh_13undmehrwohnungen INTEGER,
    anderergebaeudetyp INTEGER,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_ueberwiegender_Heizungsartt fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_gebaeude_mit_wohnraum_nach_ueberwiegender_heizungsartt (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_heizungsart NUMERIC,
    fernheizung NUMERIC,
    etagenheizung NUMERIC,
    blockheizung NUMERIC,
    zentralheizung NUMERIC,
    einzel_mehrraumoefen NUMERIC,
    keine_heizung NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Gebaeude_mit_Wohnraum_nach_ueberwiegender_Heizungsartt fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_gebaeude_mit_wohnraum_nach_ueberwiegender_heizungsartt (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_heizungsart NUMERIC,
    fernheizung NUMERIC,
    etagenheizung NUMERIC,
    blockheizung NUMERIC,
    zentralheizung NUMERIC,
    einzel_mehrraumoefen NUMERIC,
    keine_heizung NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Gebaeude_nach_Baujahr fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_gebaeude_nach_baujahr (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude INTEGER,
    vor1919 NUMERIC,
    a1919bis1949 NUMERIC,
    a1950bis1959 NUMERIC,
    a1960bis1969 NUMERIC,
    a1970bis1979 NUMERIC,
    a1980bis1989 NUMERIC,
    a1990bis1999 NUMERIC,
    a2000bis2009 NUMERIC,
    a2010bis2015 NUMERIC,
    a2016undspaeter NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Gebaeude_nach_Baujahr fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_gebaeude_nach_baujahr (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude INTEGER,
    vor1919 NUMERIC,
    a1919bis1949 NUMERIC,
    a1950bis1959 NUMERIC,
    a1960bis1969 NUMERIC,
    a1970bis1979 NUMERIC,
    a1980bis1989 NUMERIC,
    a1990bis1999 NUMERIC,
    a2000bis2009 NUMERIC,
    a2010bis2015 NUMERIC,
    a2016undspaeter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Gebaeude_nach_Baujahr_in_Mikrozensus_Klassen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_gebaeude_nach_baujahr_in_mikrozensus_klassen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude INTEGER,
    vor1919 NUMERIC,
    a1919bis1948 NUMERIC,
    a1949bis1978 NUMERIC,
    a1979bis1990 NUMERIC,
    a1991bis2000 NUMERIC,
    a2001bis2010 NUMERIC,
    a2011bis2019 NUMERIC,
    a2020undspaeter NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Gebaeude_nach_Baujahr_in_Mikrozensus_Klassen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_gebaeude_nach_baujahr_in_mikrozensus_klassen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_gebaeude INTEGER,
    vor1919 NUMERIC,
    a1919bis1948 NUMERIC,
    a1949bis1978 NUMERIC,
    a1979bis1990 NUMERIC,
    a1991bis2000 NUMERIC,
    a2001bis2010 NUMERIC,
    a2011bis2019 NUMERIC,
    a2020undspaeter NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Groesse_der_Kernfamilie fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_groesse_der_kernfamilie (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_familien INTEGER,
    a2personen INTEGER,
    a3personen INTEGER,
    a4personen INTEGER,
    a5personen INTEGER,
    a6pers_und_mehr NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Groesse_der_Kernfamilie fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_groesse_der_kernfamilie (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_familien INTEGER,
    a2personen INTEGER,
    a3personen INTEGER,
    a4personen INTEGER,
    a5personen INTEGER,
    a6pers_und_mehr NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Leerstandsquote_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_leerstandsquote_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    leerstandsquote NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Leerstandsquote_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_leerstandsquote_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    leerstandsquote NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Marktaktive_Leerstandsquote_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_marktaktive_leerstandsquote_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    marktaktive_leerstandsquote NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Marktaktive_Leerstandsquote_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_marktaktive_leerstandsquote_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    marktaktive_leerstandsquote NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Religion fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_religion (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    roemisch_katholisch NUMERIC,
    evangelisch NUMERIC,
    sonstige_keine_ohneangabe NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Religion fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_religion (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    roemisch_katholisch NUMERIC,
    evangelisch NUMERIC,
    sonstige_keine_ohneangabe NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Seniorenstatus_eines_privaten_Haushalts fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_seniorenstatus_eines_privaten_haushalts (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_haushalte INTEGER,
    hh_nursenioren NUMERIC,
    hh_mitsenioren NUMERIC,
    hh_ohnesenioren NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Seniorenstatus_eines_privaten_Haushalts fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_seniorenstatus_eines_privaten_haushalts (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_haushalte INTEGER,
    hh_nursenioren NUMERIC,
    hh_mitsenioren NUMERIC,
    hh_ohnesenioren NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Typ_der_Kernfamilie_nach_Kindern fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_typ_der_kernfamilie_nach_kindern (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_familie NUMERIC,
    ehep_ohnekind NUMERIC,
    ehep_mind_1kind_unter18 NUMERIC,
    ehep_kinder_ab18 NUMERIC,
    eingetrlp_ohnekind NUMERIC,
    eingetrlp_mind_1kind_unter18 NUMERIC,
    eingetrlp_kinder_ab18 NUMERIC,
    nichtehellg_ohnekind NUMERIC,
    nichtehellg_mind_1kind_unter18 NUMERIC,
    nichtehellg_kinder_ab18 NUMERIC,
    vater_mind_1kind_unter18 NUMERIC,
    vater_kinder_ab18 NUMERIC,
    mutter_mind_1kind_unter18 NUMERIC,
    mutter_kinder_ab18 NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Typ_der_Kernfamilie_nach_Kindern fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_typ_der_kernfamilie_nach_kindern (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_familie NUMERIC,
    ehep_ohnekind NUMERIC,
    ehep_mind_1kind_unter18 NUMERIC,
    ehep_kinder_ab18 NUMERIC,
    eingetrlp_ohnekind NUMERIC,
    eingetrlp_mind_1kind_unter18 NUMERIC,
    eingetrlp_kinder_ab18 NUMERIC,
    nichtehellg_ohnekind NUMERIC,
    nichtehellg_mind_1kind_unter18 NUMERIC,
    nichtehellg_kinder_ab18 NUMERIC,
    vater_mind_1kind_unter18 NUMERIC,
    vater_kinder_ab18 NUMERIC,
    mutter_mind_1kind_unter18 NUMERIC,
    mutter_kinder_ab18 NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Typ_des_privaren_Haushalts_Lebensform fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_typ_des_privaren_haushalts_lebensform (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_haushalte INTEGER,
    einpershh_singlehh NUMERIC,
    ehepaare NUMERIC,
    eingetrlebensp NUMERIC,
    nichtehellebensg NUMERIC,
    alleinerzmuetter NUMERIC,
    alleinerzvaeter NUMERIC,
    mehrpershhohnekernfam NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Typ_des_privaren_Haushalts_Lebensform fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_typ_des_privaren_haushalts_lebensform (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_haushalte INTEGER,
    einpershh_singlehh NUMERIC,
    ehepaare NUMERIC,
    eingetrlebensp NUMERIC,
    nichtehellebensg NUMERIC,
    alleinerzmuetter NUMERIC,
    alleinerzvaeter NUMERIC,
    mehrpershhohnekernfam NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Typ_des_privaten_Haushalts_Familien fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_typ_des_privaten_haushalts_familien (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_haushalte INTEGER,
    einpershh_singlehh NUMERIC,
    paare_ohnekind NUMERIC,
    paare_mitkind NUMERIC,
    alleinerziehende NUMERIC,
    mehrpershhohnekernfam NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Typ_des_privaten_Haushalts_Familien fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_typ_des_privaten_haushalts_familien (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_haushalte INTEGER,
    einpershh_singlehh NUMERIC,
    paare_ohnekind NUMERIC,
    paare_mitkind NUMERIC,
    alleinerziehende NUMERIC,
    mehrpershhohnekernfam NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Wohnungen_nach_Gebaeudetyp_Groesse fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_wohnungen_nach_gebaeudetyp_groesse (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_wohnungen INTEGER,
    freiefh NUMERIC,
    efh_dhh NUMERIC,
    efh_reihenhaus NUMERIC,
    freist_zfh NUMERIC,
    zfh_dhh NUMERIC,
    zfh_reihenhaus NUMERIC,
    mfh_3bis6wohnungen INTEGER,
    mfh_7bis12wohnungen INTEGER,
    mfh_13undmehrwohnungen INTEGER,
    anderergebaeudetyp INTEGER,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Wohnungen_nach_Gebaeudetyp_Groesse fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_wohnungen_nach_gebaeudetyp_groesse (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_wohnungen INTEGER,
    freiefh NUMERIC,
    efh_dhh NUMERIC,
    efh_reihenhaus NUMERIC,
    freist_zfh NUMERIC,
    zfh_dhh NUMERIC,
    zfh_reihenhaus NUMERIC,
    mfh_3bis6wohnungen INTEGER,
    mfh_7bis12wohnungen INTEGER,
    mfh_13undmehrwohnungen INTEGER,
    anderergebaeudetyp INTEGER,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Wohnungen_nach_Zahl_der_Raeume fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_wohnungen_nach_zahl_der_raeume (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_wohnungen INTEGER,
    1raum NUMERIC,
    2raeume INTEGER,
    3raeume INTEGER,
    4raeume INTEGER,
    5raeume INTEGER,
    6raeume INTEGER,
    7undmehrraeume INTEGER,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Wohnungen_nach_Zahl_der_Raeume fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_wohnungen_nach_zahl_der_raeume (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_wohnungen INTEGER,
    1raum NUMERIC,
    2raeume INTEGER,
    3raeume INTEGER,
    4raeume INTEGER,
    5raeume INTEGER,
    6raeume INTEGER,
    7undmehrraeume INTEGER,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Zahl_der_Staatsangehoerigkeiten fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_zahl_der_staatsangehoerigkeiten (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    einestaatsang NUMERIC,
    mehrere_deutsch_und_auslaendisch NUMERIC,
    mehrere_nur_auslaendisch NUMERIC,
    nicht_bekannt NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Zahl_der_Staatsangehoerigkeiten fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_zahl_der_staatsangehoerigkeiten (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    einestaatsang NUMERIC,
    mehrere_deutsch_und_auslaendisch NUMERIC,
    mehrere_nur_auslaendisch NUMERIC,
    nicht_bekannt NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Zensus2022_Bevoelkerungszahl fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_zensus2022_bevoelkerungszahl (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    einwohner INTEGER,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Zensus2022_Bevoelkerungszahl fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_zensus2022_bevoelkerungszahl (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    einwohner INTEGER,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Zensus2022_Durchschn_Nettokaltmiete(1) fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_zensus2022_durchschn_nettokaltmiete_1_ (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnmieteqm NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Zensus2022_Durchschn_Nettokaltmiete(1) fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_zensus2022_durchschn_nettokaltmiete_1_ (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    durchschnmieteqm NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Zensus2022_Energietraeger fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_zensus2022_energietraeger (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_energietraeger NUMERIC,
    gas NUMERIC,
    heizoel NUMERIC,
    holz_holzpellets NUMERIC,
    biomasse_biogas NUMERIC,
    solar_geothermie_waermepumpen NUMERIC,
    strom NUMERIC,
    kohle NUMERIC,
    fernwaerme NUMERIC,
    kein_energietraeger NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Zensus2022_Energietraeger fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_zensus2022_energietraeger (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_energietraeger NUMERIC,
    gas NUMERIC,
    heizoel NUMERIC,
    holz_holzpellets NUMERIC,
    biomasse_biogas NUMERIC,
    solar_geothermie_waermepumpen NUMERIC,
    strom NUMERIC,
    kohle NUMERIC,
    fernwaerme NUMERIC,
    kein_energietraeger NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Zensus2022_Geburtsland_Gruppen_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_zensus2022_geburtsland_gruppen_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    deutschland NUMERIC,
    ausland_sonstige NUMERIC,
    eu27_land NUMERIC,
    sonstiges_europa NUMERIC,
    sonstige_welt NUMERIC,
    sonstige NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Zensus2022_Geburtsland_Gruppen_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_zensus2022_geburtsland_gruppen_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    deutschland NUMERIC,
    ausland_sonstige NUMERIC,
    eu27_land NUMERIC,
    sonstiges_europa NUMERIC,
    sonstige_welt NUMERIC,
    sonstige NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Zensus2022_Groesse_des_privaten_Haushalts_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_zensus2022_groesse_des_privaten_haushalts_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    1_person NUMERIC,
    2_personen INTEGER,
    3_personen INTEGER,
    4_personen INTEGER,
    5_personen INTEGER,
    6_personen_und_mehr INTEGER,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Zensus2022_Groesse_des_privaten_Haushalts_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_zensus2022_groesse_des_privaten_haushalts_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    1_person NUMERIC,
    2_personen INTEGER,
    3_personen INTEGER,
    4_personen INTEGER,
    5_personen INTEGER,
    6_personen_und_mehr INTEGER,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Zensus2022_Heizungsart fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_zensus2022_heizungsart (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_heizungsart NUMERIC,
    fernheizung NUMERIC,
    etagenheizung NUMERIC,
    blockheizung NUMERIC,
    zentralheizung NUMERIC,
    einzel_mehrraumoefen NUMERIC,
    keine_heizung NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Zensus2022_Heizungsart fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_zensus2022_heizungsart (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_heizungsart NUMERIC,
    fernheizung NUMERIC,
    etagenheizung NUMERIC,
    blockheizung NUMERIC,
    zentralheizung NUMERIC,
    einzel_mehrraumoefen NUMERIC,
    keine_heizung NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Zensus2022_Staatsangehoerigkeit_Gruppen_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_zensus2022_staatsangehoerigkeit_gruppen_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    deutschland NUMERIC,
    ausland_sonstige NUMERIC,
    eu27_land NUMERIC,
    sonstiges_europa NUMERIC,
    sonstige_welt NUMERIC,
    sonstige NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Zensus2022_Staatsangehoerigkeit_Gruppen_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_zensus2022_staatsangehoerigkeit_gruppen_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    deutschland NUMERIC,
    ausland_sonstige NUMERIC,
    eu27_land NUMERIC,
    sonstiges_europa NUMERIC,
    sonstige_welt NUMERIC,
    sonstige NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);


-- Zensus2022_Staatsangehoerigkeit_in_Gitterzellen fact table for 1km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_1km_zensus2022_staatsangehoerigkeit_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    deutschland NUMERIC,
    ausland_sonstige NUMERIC,
    x_mp_1km NUMERIC,
    y_mp_1km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_1km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_1km(grid_id)
);


-- Zensus2022_Staatsangehoerigkeit_in_Gitterzellen fact table for 10km grid
CREATE TABLE IF NOT EXISTS zensus.fact_zensus_10km_zensus2022_staatsangehoerigkeit_in_gitterzellen (
    grid_id TEXT PRIMARY KEY,
    year INTEGER NOT NULL DEFAULT 2022,
    insgesamt_bevoelkerung INTEGER,
    deutschland NUMERIC,
    ausland_sonstige NUMERIC,
    x_mp_10km NUMERIC,
    y_mp_10km NUMERIC,
    CONSTRAINT chk_year_2022 CHECK (year = 2022),
    CONSTRAINT fk_grid_10km FOREIGN KEY (grid_id) REFERENCES zensus.ref_grid_10km(grid_id)
);

